# Generated by Django 3.2.5 on 2021-07-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
