# Generated by Django 3.2.5 on 2021-07-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_newuser_is_active'),
        ('course', '0003_alter_course_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.faculty'),
        ),
    ]
