# Generated by Django 3.2.5 on 2021-07-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_faculty_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
    ]
