# Generated by Django 3.2.5 on 2021-07-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
