# Generated by Django 3.2.5 on 2021-07-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210715_2156'),
        ('person', '0008_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='course.course'),
        ),
    ]
