# Generated by Django 3.2.5 on 2021-07-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210715_2156'),
        ('person', '0010_auto_20210716_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, related_name='courseStudentBridge', to='course.course'),
        ),
    ]
