# Generated by Django 3.2.5 on 2021-07-21 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_tododata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tododata',
            old_name='dateTime',
            new_name='created',
        ),
        migrations.AddField(
            model_name='tododata',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 20, 24, 8, 288866)),
        ),
    ]
