# Generated by Django 3.2.5 on 2021-07-21 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_auto_20210721_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 20, 25, 36, 245575)),
        ),
    ]
