# Generated by Django 3.2.5 on 2021-07-21 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0014_alter_tododata_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododata',
            name='title',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 23, 16, 57, 716135)),
        ),
    ]
