# Generated by Django 3.2.5 on 2021-07-23 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210715_2156'),
        ('person', '0015_auto_20210721_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 23, 25, 29, 287743)),
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.CharField(default='', max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.student')),
            ],
        ),
    ]
