# Generated by Django 3.2.5 on 2021-07-23 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210715_2156'),
        ('person', '0016_auto_20210723_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 0, 23, 32, 18278)),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together={('course', 'student')},
        ),
    ]
