# Generated by Django 3.2.5 on 2021-07-24 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210715_2156'),
        ('person', '0018_alter_tododata_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 15, 41, 31, 593304)),
        ),
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredCredits', models.IntegerField(default=3)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.programme')),
            ],
        ),
    ]
