# Generated by Django 3.2.5 on 2021-07-24 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20210715_2156'),
        ('person', '0019_auto_20210724_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 15, 42, 36, 421404)),
        ),
        migrations.AlterUniqueTogether(
            name='creditmodel',
            unique_together={('program', 'cat')},
        ),
    ]
