# Generated by Django 3.2.5 on 2021-07-24 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_auto_20210724_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='rating',
            field=models.CharField(blank=True, default=0, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 0, 33, 21, 772740)),
        ),
    ]
