# Generated by Django 3.2.5 on 2021-07-25 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_auto_20210725_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 25, 12, 58, 3, 676501)),
        ),
    ]
